name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build docker builder
        run: docker build . -t ci

      - name: Build and test plugin
        run: docker run --network none --env GOPATH="" --rm -v $PWD:/go/work ci make build

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Archive production artifacts
        run: |
          cp ./build/argocd-tag-plugin ./argocd-tag-plugin-${{ steps.get_version.outputs.VERSION }}-x86_64
          tar -zcvf argocd-tag-plugin-${{ steps.get_version.outputs.VERSION }}-x86_64.tar.gz ./argocd-tag-plugin-${{ steps.get_version.outputs.VERSION }}-x86_64

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: argocd-tag-plugin-${{ steps.get_version.outputs.VERSION }}-x86_64.tar.gz
          path: ./argocd-tag-plugin-${{ steps.get_version.outputs.VERSION }}-x86_64.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: argocd-tag-plugin-${{ steps.get_version.outputs.VERSION }}-x86_64.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "./argocd-tag-plugin-${{ steps.get_version.outputs.VERSION }}-x86_64.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
